version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=php
        - PHP_UPSTREAM_PORT=9000
        - APP_CODE_PATH_HOST=${APP_CODE_PATH_HOST}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - ./app:/var/www/app
    networks:
      - backpack
    ports:
      - ${PHP_NGINX_HOST_PORT:-8081}:80

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}

    volumes:
      - ./app:/var/www/app
    ports:
      - ${PHP_FPM_HOST_PORT:-9000}:9000
    networks:
      - backpack

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_DATABASE: redemption
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - db:/var/lib/mysql/
    ports:
      - ${DB_HOST_PORT:-3306}:3306
    networks:
      - backpack
    restart: unless-stopped

networks:
  backpack:
    driver: bridge

volumes:
  db:
